### ISSUE TITLE
Using large fonts in a11y settings causes panel to grow

### ISSUE THREAD

**Issue by danrabbit** [elementary/wingpanel-indicator-keyboard#10]
Originally reported at https://github.com/elementary/wingpanel/issues/23

![13707888](https://cloud.githubusercontent.com/assets/7277719/25565976/3c2ed33e-2d86-11e7-897a-8cf61dbd1464.png)

**Comment by Cluster19** [comment]
There was no such a probleb one week ago. Then  volume indicator went up and yesterday that funny picture appeared
