### ISSUE TITLE
Ibus daemon should be started if necessary when ibus input methods are in use

### ISSUE THREAD

**Issue by jeremypw** [elementary/wingpanel-indicator-keyboard#105]
## Problem

When setting up ibus input methods with the switchboard plug it is necessary to turn the ibus daemon on (and the means to do so is provided).  However after rebooting the ibus daemon is not restarted and the configured input method is not available.  At the moment it is necessary to use a custom startup command to start ibus.

## Proposal

The wingpanel indicator automatically starts the ibus daemon if there are ibus sources configured.

**Comment by ryonakano** [comment]
FYI I'm using elementary OS in Japanese and ibus-daemon starts automatically on login. It seems to autostart on CJK environment for some reason. IIRC, however, this behavior is different from the upstream, Ubuntu: ibus-daemon starts automatically in English system (I tested in en_US) on login. I personally think we may want to match the behavior with Ubuntu, not adding a code that autostarts ibus-daemon into Keyboard Indicator. Not sure what's causing this different behavior though.

**Comment by jeremypw** [comment]
This Ubuntu wiki https://help.ubuntu.com/community/ibus suggests ibus does not always start even on ubuntu.  Another possibility would be to make the switchboard plug add ibus-daemon to autostart as part of the page that shows when ibus is not running.  The option will not then show when it is not needed.

**Comment by danrabbit** [comment]
Fixed in https://github.com/elementary/switchboard-plug-keyboard/pull/374
