### ISSUE TITLE
Keyboard layout does not change properly

### ISSUE THREAD

**Issue by Condor157** [elementary/wingpanel-indicator-keyboard#108]
When changing keyboard layout, it does  not change from the first time.
 Steps to reproduce:
1. Set Russian and English(US) layout. 
2. Switch between them.
3. When you switch from Engish to Russian you have to push buttons twice.
Check it.
Also it swithes too long about 0.3 s.

**Comment by jeremypw** [comment]
Which keyboard shortcut are you using to switch layouts? I cannot reproduce this using `<Alt><Shift>`.  You can choose different key combinations to switch layouts using System Settings.
