### ISSUE TITLE
Keyboard indicator open System Settings instead of keyboard settings

### ISSUE THREAD

**Issue by popvladaurel** [elementary/wingpanel-indicator-keyboard#12]
After adding a new language, the keyboard indicator appears in the Wingpanel. Clicking on it and then on "Keyboard Settings..." launches System Settings instead of Keyboard plug.
![kazam_screencast_00000](https://cloud.githubusercontent.com/assets/23455688/25653678/a6ab8ef6-2ff6-11e7-8929-f0b4c314100f.gif)

**Comment by danrabbit** [comment]
Fixed in #11
