### ISSUE TITLE
doesn't compile successfully against granite+wingpanel git master

### ISSUE THREAD

**Issue by decathorpe** [elementary/wingpanel-indicator-keyboard#23]
This project now fails to build for me with the same error as the Bluetooth Indicator, reported [here](https://github.com/elementary/wingpanel-indicator-bluetooth/issues/29).

The build logs look like this:

```
(...)/src/LayoutButton.vala:28.9-28.26: error: The name `get_content_widget' does not exist in the context of `Keyboard.Widgets.LayoutButton.new'
        get_content_widget ().add (radio_button);
        ^^^^^^^^^^^^^^^^^^
make[2]: *** [src/CMakeFiles/keyboard.dir/build.make:84: src/keyboard_valac.stamp] Error 1
make[2]: Leaving directory '(...)'
make[1]: *** [CMakeFiles/Makefile2:120: src/CMakeFiles/keyboard.dir/all] Error 2
make: *** [Makefile:133: all] Error 2
```

The apparently "missing" `get_content_widget` is defined in `wingpanel/lib/Widgets/Container.vala`, but can't be found here.

**Comment by ricotz** [comment]
See https://github.com/elementary/wingpanel/pull/48

**Comment by decathorpe** [comment]
This issue has been resolved by the fix committed to wingpanel. Thanks!
