### ISSUE TITLE
[Suggestion] Caps Lock indication

### ISSUE THREAD

**Issue by robertgorbul** [elementary/wingpanel-indicator-keyboard#25]
Is it possible to add some sort of indication to the keyboard indicator when Caps Lock is active?
My first thought is to change label case on caps activated.
Well, we can call it a "little nice feature". Feel free to close this, just wanted to share my thoughts on this.

**Comment by Djaler** [comment]
Sounds nice for me

**Comment by cassidyjames** [comment]
I am on board with this if it's off by default (most hardware should have a physical indicator somewhere), and we can add a setting to _System Settings_ → _Keyboard_ somewhere.
