### ISSUE TITLE
Slow keyboard layouts switch [$10]

### ISSUE THREAD

**Issue by d1moncom** [elementary/wingpanel-indicator-keyboard#43]
I use a keyboard with two layouts - EN (english) and RU (russian). Switching between layouts tried buttons ALT+SHIFT and CTRL+SHIFT. Switching occurs with a delay of about a second. Because of this, when I switch and start typing, the first letter of word  obtained in a different layout. It is very uncomfortable.

Demo: йййййй йqqqqqq ййййййй йqqqqq ййййййй ййqqqqq ййййййййй ййqqqqqq ййййййй qqqqqqqq ййййййй йqqqqqqq йqqqqqqqqq ййййййййй

**Comment by Ladone** [comment]
I have the same problem :c

**Comment by peteruithoven** [comment]
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/gala/issues/220

**Comment by peteruithoven** [comment]
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/gala/issues/220

**Comment by jeremypw** [comment]
As this is closed, does the bounty need transferring?

**Comment by peteruithoven** [comment]
@d1moncom Could you transfer your bounty for elementary/gala#220?

**Comment by Ladone** [comment]
My problem was that I confused global variables and pasted code where the loop with windows was initialized.
