### ISSUE TITLE
Add a screenshot in the readme

### ISSUE THREAD

**Issue by ryonakano** [elementary/wingpanel-indicator-keyboard#53]

**Comment by khanaaziz1** [comment]
can you explain what you want to do?

**Comment by ryonakano** [comment]
@khanaaziz1 You need to take a screenshot of this indicator in elementary OS and then add it to the README.md in the Markdown style: `![Alt Attribute](path/to/screenshot.png)`.

So the consequence of the README.md looks like this (this is only the top part though):

```markdown
# Wingpanel Keyboard Indicator
[![l10n](https://l10n.elementary.io/widgets/wingpanel/wingpanel-indicator-keyboard/svg-badge.svg)](https://l10n.elementary.io/projects/wingpanel/wingpanel-indicator-keyboard)

![Screenshot](data/screenshot.png?raw=true)

## Building and Installation
…(some lines follow)
```

See also other repositories of Wingpanel Indicators e.g. https://github.com/elementary/wingpanel-indicator-session/blob/master/README.md
