### ISSUE TITLE
White text on white background.

### ISSUE THREAD

**Issue by ovishchuk** [elementary/wingpanel-indicator-keyboard#56]
Text is almost unreadable. And indicator stands out from the overall design of panel.
![Знімок з 2019-11-01 12-20-55](https://user-images.githubusercontent.com/42047832/68018564-1ba1c980-fca2-11e9-9725-385ecd239abc.png)
![Знімок з 2019-11-01 12-19-04](https://user-images.githubusercontent.com/42047832/68018489-f01edf00-fca1-11e9-9137-41950b18dce9.png)

**Comment by ryonakano** [comment]
Seems like a regression of #47

**Comment by ryonakano** [comment]
[According to Cassidy](https://github.com/elementary/wingpanel-indicator-keyboard/pull/57#issuecomment-548828220), this already fixed in elementary/stylesheet#536, but a new release of stylesheet has not been published.

**Comment by Exalm** [comment]
It hasn't been fixed. The fix is for `keycap` style class, while the panel uses `keyboard` and doesn't look correct with `keycap` either.

**Comment by Exalm** [comment]
I take my words back, it is fixed in the daily builds. I assume a new release of the indicator was also needed.

**Comment by o-alquimista** [comment]
[Release 2.2.0](https://github.com/elementary/wingpanel-indicator-keyboard/releases/tag/2.2.0) fixed it. I already received the update.
