### ISSUE TITLE
layout indicator is not displayed

### ISSUE THREAD

**Issue by labi-le** [elementary/wingpanel-indicator-keyboard#79]

**Comment by michaljenicek** [comment]
Hi, I'm having the same issue, on Elementary 5.1.7 Hera when I add another keyboard layout, the keyboard indicator doesn't appear (even though package is installed), I even tried manually building it according to your instructions, but it doesn't appear.

Do you have any ideas what could be the problem?

Thank you.

**Comment by ryonakano** [comment]
Closing as a duplicate of #80
