### ISSUE TITLE
No keyboard/language indicator.

### ISSUE THREAD

**Issue by eliaskas** [elementary/wingpanel-indicator-keyboard#80]
There is no keyboard or language indicator on the top panel at the right side corner.
I use US English and Greek keyboard and I have a serious problem in changing languages.
Thank you

**Comment by tintou** [comment]
There should be if you have both keyboards showing in the System Settings, can you take a screenshot of the Keyboard section of the System Settings to make sure that it's correctly set?

**Comment by ryonakano** [comment]
Not him, but I can also confirm this issue on odin:

![Screenshot from 2020-11-06 10-48-10](https://user-images.githubusercontent.com/26003928/98316425-b9e70e80-201d-11eb-9cdb-d2a03d11f70e.png)

If I added three layouts the indicator appears but there are only two layouts shown:

![Screenshot from 2020-11-06 10-48-39](https://user-images.githubusercontent.com/26003928/98316439-beabc280-201d-11eb-8ad3-05d40ab9c315.png)

**Comment by Marukesu** [comment]
I think the problem is that the indicator ignores any input method that uses ibus.

**Comment by ryonakano** [comment]
Hmm, I don't think it is the cause of this issue. The indicator ignores ibus sources for a long time but I didn't face this issue before.

**Comment by michaljenicek** [comment]
I have the same issue, however, in my case the indicator doesn't show even if I add both English (UK) and English (US) keyboard layouts as shown in the picture above.

**Comment by Marukesu** [comment]
So, when i was adding some layouts to see if they appear and, for no reason, it changed one of the xkb layouts to ibus. But i can't reproduce it anymore.

**Comment by Marukesu** [comment]
here, it's was to be `('xkb', 'br')` and was before i added the english layout.
```
$ gsettings get org.gnome.desktop.input-sources sources
[('ibus', 'br'), ('ibus', 'jp'), ('xkb', 'us')]
```

**Comment by rekkabell** [comment]
My keyboard/language indicator disappears when I remove a language, even if I have a minimum of two. To make it appear again, I've got to remove all languages, and to add them again. 
Also, on top of that, only default language works. Even if the indicator is there, the language keyboard switch isn't happening. Tested French (CA) and Japanese (Kana). Could this be related? (Updated to 5.1.7 Hera, recently. No keyboard problems before that.)

**Comment by jeremypw** [comment]
So, this appears to be due to three issues in combination: 
1) The indicator does not show if there is only one visible layout
2) Only xkb sources are visible
3) Under some circumstances xkb sources get saved in the settings as ibus sources.

I am working on some related PRs and will try to fix this there.

**Comment by jeremypw** [comment]
A workround  is to remove all keyboard layouts and re-add, but a recent change to the switchboard-plug-keyboard prevents this so you have to use dconf-editor to change org.gnome.desktop.input-sources.sources

**Comment by michaljenicek** [comment]
> A workround is to remove all keyboard layouts and re-add, but a recent change to the switchboard-plug-keyboard (master) prevents this so you have to use dconf-editor to change org.gnome.desktop.input-sources.sources

This workaround seems to have fixed the issue for me, the indicator shows now, thank you.

**Comment by jeremypw** [comment]
Note: I could only reproduce this when I had an ibus engine installed.
