### ISSUE TITLE
Keyboard layout indicator don't display layouts

### ISSUE THREAD

**Issue by ghost** [elementary/wingpanel-indicator-keyboard#91]
1) I use clean os (after installation) 
![Screenshot from 2021-01-02 23-55-11](https://user-images.githubusercontent.com/44160260/103464547-55fb7080-4d56-11eb-98e6-3b378e50e36e.png)

**Comment by jeremypw** [comment]
Sounds similar to #80, for which a fix has recently been merged into master.

**Comment by svetley1** [comment]
Does this mean that the problem should be resolved in 5.1.7?
If so, the problem remains.

**Comment by jeremypw** [comment]
Well, the wingpanel keyboard indicator does still build on Hera but unfortunately it needs the latest version of the switchboard keyboard plug to work properly and the switchboard plug no longer builds on Hera because it now uses libhandy. So unfortunately I think the fix will have to wait for Odin release.

**Comment by ttm56p** [comment]
I use 5.1.7, I have checked for updates in app center. There are none.
I do have problem and it appeared just recently.
I communicate via multiple languages and considering that E-OS is my main linux os - issue is critical for me.
Multi-language support is definitely weak point of Elementary OS.
----------------
@jeremypw is it possible to address that issue by building/installing older switchboard plug version?

**Comment by jeremypw** [comment]
@ttm56p It is probably possible to fork an older plug version and backport the recent fix into it but it would have to be done by a third party.

**Comment by shved** [comment]
@svetley1 I had the same issue. See my reddit post on how to fix it https://www.reddit.com/r/elementaryos/comments/ks8ndy/keyboard_layout_indicator_is_missing_on_wingpanel/

**Comment by lazaroofarrill** [comment]
@shved Oh my god thanks, that was really driving me crazy.

**Comment by vlaczas** [comment]
I solved this issue by deleting all layouts and then readded them back. Seems OS doesn't count the languages that you add during the installation process. So, after the installation you need to declare them again.

**Comment by lenemter** [comment]
Seems like the issue was fixed in OS 6.
